# Internship Week 1: SQL and Python

**Objective:** To practice SQL queries, data manipulation, and basic data analysis using Python and Pandas.

**Tools Used:** Google Colab, SQLite, SQL, Python, Pandas

In [33]:
import sqlite3
import pandas as pd

# Create a temporary database
connection = sqlite3.connect(":memory:")

# Create student table
connection.execute("""
CREATE TABLE students (
    Student_ID INTEGER,
    Name TEXT,
    Department TEXT,
    Attendance INTEGER,
    Study_Hours INTEGER,
    Assignment_Marks INTEGER,
    Internal_Marks INTEGER,
    Final_Marks INTEGER
)
""")

# Add student data
students = [
    (101, "Aarav", "BCS", 85, 4, 82, 78, 80),
    (102, "Priya", "BCS", 72, 3, 70, 68, 69),
    (103, "Rahul", "BCA", 91, 6, 88, 85, 87),
    (104, "Sneha", "BCS", 68, 2, 65, 62, 64),
    (105, "Aditya", "BCA", 88, 5, 85, 82, 84),
    (106, "Neha", "BCS", 95, 7, 92, 90, 91),
    (107, "Rohan", "BCA", 76, 3, 72, 70, 71),
    (108, "Ananya", "BCS", 82, 5, 80, 76, 79),
    (109, "Vikram", "BCA", 65, 2, 60, 58, 61),
    (110, "Pooja", "BCS", 90, 6, 89, 87, 88)
]

connection.executemany(
    "INSERT INTO students VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
    students
)

# Display the table
pd.read_sql_query("SELECT * FROM students", connection)

,Student_ID,Name,Department,Attendance,Study_Hours,Assignment_Marks,Internal_Marks,Final_Marks
0,101,Aarav,BCS,85,4,82,78,80
1,102,Priya,BCS,72,3,70,68,69
2,103,Rahul,BCA,91,6,88,85,87
3,104,Sneha,BCS,68,2,65,62,64
4,105,Aditya,BCA,88,5,85,82,84
5,106,Neha,BCS,95,7,92,90,91
6,107,Rohan,BCA,76,3,72,70,71
7,108,Ananya,BCS,82,5,80,76,79
8,109,Vikram,BCA,65,2,60,58,61
9,110,Pooja,BCS,90,6,89,87,88

## Part 1: SQL Practice

Topics covered: SELECT, WHERE, ORDER BY, GROUP BY, HAVING, duplicate values, INNER JOIN, and LEFT JOIN.

In [34]:
query = """
SELECT * FROM students;
"""
result = pd.read_sql_query(query, connection)
result

,Student_ID,Name,Department,Attendance,Study_Hours,Assignment_Marks,Internal_Marks,Final_Marks
0,101,Aarav,BCS,85,4,82,78,80
1,102,Priya,BCS,72,3,70,68,69
2,103,Rahul,BCA,91,6,88,85,87
3,104,Sneha,BCS,68,2,65,62,64
4,105,Aditya,BCA,88,5,85,82,84
5,106,Neha,BCS,95,7,92,90,91
6,107,Rohan,BCA,76,3,72,70,71
7,108,Ananya,BCS,82,5,80,76,79
8,109,Vikram,BCA,65,2,60,58,61
9,110,Pooja,BCS,90,6,89,87,88

In [35]:
query = """
SELECT Name, Department, Final_Marks
FROM students;
"""

result = pd.read_sql_query(query, connection)
result

     Name Department  Final_Marks
0   Aarav        BCS           80
1   Priya        BCS           69
2   Rahul        BCA           87
3   Sneha        BCS           64
4  Aditya        BCA           84
5    Neha        BCS           91
6   Rohan        BCA           71
7  Ananya        BCS           79
8  Vikram        BCA           61
9   Pooja        BCS           88

In [36]:
query = """
SELECT Name, Final_Marks
FROM students
ORDER BY Final_Marks DESC;
"""

result = pd.read_sql_query(query, connection)
result

     Name  Final_Marks
0    Neha           91
1   Pooja           88
2   Rahul           87
3  Aditya           84
4   Aarav           80
5  Ananya           79
6   Rohan           71
7   Priya           69
8   Sneha           64
9  Vikram           61

In [37]:
 query="""SELECT Department,AVG(Final_Marks) AS Average_Marks
From students
GROUP BY Department; """
result = pd.read_sql_query(query,connection)
result

  Department  Average_Marks
0        BCA          75.75
1        BCS          78.50

In [38]:
query = """
SELECT Department, AVG(Final_Marks) AS Average_Marks
FROM students
GROUP BY Department
HAVING AVG(Final_Marks) > 75;
"""

result = pd.read_sql_query(query, connection)
result

  Department  Average_Marks
0        BCA          75.75
1        BCS          78.50

In [39]:
connection.execute("""
INSERT INTO students VALUES
(111, 'Aarav', 'BCA', 80, 4, 75, 70, 74)
""")

In [40]:
query = """
SELECT Name, COUNT(*) AS Count
FROM students
GROUP BY Name
HAVING COUNT(*) > 1;
"""

result = pd.read_sql_query(query, connection)
result

    Name  Count
0  Aarav      2

In [41]:
connection.execute("""
CREATE TABLE departments (
    Department TEXT,
    HOD TEXT
)
""")

departments = [
    ("BCS", "Dr. Mehta"),
    ("BCA", "Dr. Sharma")
]

connection.executemany(
    "INSERT INTO departments VALUES (?, ?)",
    departments
)

In [42]:
query = """
SELECT students.Name, students.Department, departments.HOD
FROM students
INNER JOIN departments
ON students.Department = departments.Department;
"""

result = pd.read_sql_query(query, connection)
result

      Name Department         HOD
0    Aarav        BCS   Dr. Mehta
1    Priya        BCS   Dr. Mehta
2    Rahul        BCA  Dr. Sharma
3    Sneha        BCS   Dr. Mehta
4   Aditya        BCA  Dr. Sharma
5     Neha        BCS   Dr. Mehta
6    Rohan        BCA  Dr. Sharma
7   Ananya        BCS   Dr. Mehta
8   Vikram        BCA  Dr. Sharma
9    Pooja        BCS   Dr. Mehta
10   Aarav        BCA  Dr. Sharma

In [43]:
query = """
SELECT students.Name, students.Department, departments.HOD
FROM students
LEFT JOIN departments
ON students.Department = departments.Department;
"""

result = pd.read_sql_query(query, connection)
result

      Name Department         HOD
0    Aarav        BCS   Dr. Mehta
1    Priya        BCS   Dr. Mehta
2    Rahul        BCA  Dr. Sharma
3    Sneha        BCS   Dr. Mehta
4   Aditya        BCA  Dr. Sharma
5     Neha        BCS   Dr. Mehta
6    Rohan        BCA  Dr. Sharma
7   Ananya        BCS   Dr. Mehta
8   Vikram        BCA  Dr. Sharma
9    Pooja        BCS   Dr. Mehta
10   Aarav        BCA  Dr. Sharma

## Part 2: Python Practice

**Topics Covered:** Filtering data, calculating averages, finding maximum marks, counting students by department, identifying low attendance, and sorting data using Pandas.

**Prompt 1: Filter Students**

Write Python code using Pandas to display students whose final marks are greater than 80.

In [44]:
df = pd.read_sql_query("SELECT*FROM students",connection)
result = df[df["Final_Marks"]>80]
result

,Student_ID,Name,Department,Attendance,Study_Hours,Assignment_Marks,Internal_Marks,Final_Marks
2,103,Rahul,BCA,91,6,88,85,87
4,105,Aditya,BCA,88,5,85,82,84
5,106,Neha,BCS,95,7,92,90,91
9,110,Pooja,BCS,90,6,89,87,88

**Prompt 2: Average Marks**

Write Python code using Pandas to calculate the average final marks of all students.

In [45]:
average_marks=df["Final_Marks"].mean()
print("Average Final Marks:",average_marks)

Average Final Marks: 77.0909090909091

In [46]:
average_marks=df["Final_Marks"].mean()
print("Average Final Marks:",round (average_marks,2))

Average Final Marks: 77.09

**Prompt 3: Highest Marks**

Write Python code using Pandas to find the student who scored the highest final marks.

In [48]:
top_student = df.loc[df["Final_Marks"].idxmax()]
print(top_student[["Name","Final_Marks"]])

Name           Neha
Final_Marks      91
Name: 5, dtype: object

**Prompt 4: Department-wise Student Count**

Write Python code using Pandas to count the number of students in each department.

In [52]:
department_count = df["Department"].value_counts()
print (department_count)

Department
BCS    6
BCA    5
Name: count, dtype: int64

**Prompt 5: Low Attendance**

Write Python code using Pandas to display students whose attendance is below 75%.

In [50]:
low_attendance = df[df["Attendance"]<75]
low_attendance

,Student_ID,Name,Department,Attendance,Study_Hours,Assignment_Marks,Internal_Marks,Final_Marks
1,102,Priya,BCS,72,3,70,68,69
3,104,Sneha,BCS,68,2,65,62,64
8,109,Vikram,BCA,65,2,60,58,61

**Prompt 6: Sort Final Marks**

Write Python code using Pandas to sort students by final marks from highest to lowest.

In [51]:
sorted_students = df.sort_values(by="Final_Marks",ascending=False)
sorted_students [["Name","Final_Marks"]]

      Name  Final_Marks
5     Neha           91
9    Pooja           88
2    Rahul           87
4   Aditya           84
0    Aarav           80
7   Ananya           79
10   Aarav           74
6    Rohan           71
1    Priya           69
3    Sneha           64
8   Vikram           61